# Juntar ficheros en uno único

Para poder realizar el estudio, vamos a juntar todos los ficheros (con datos diarios de cada año) en un único.

In [1]:
# Librerias 
import os
import pandas as pd

In [3]:
# Cargar en una lista los nombres de todos los archivos
fileList = os.listdir()

# Dejar solo los archivos  que son de tipo csv
listCsv = [file for file in fileList if file[-3:] == "csv"]

# Crear dataframe vacio
df = pd.DataFrame()

# Recorrer la lista de archivos y unirlos
for file in listCsv:
    ftemp = pd.read_csv(file, delimiter = ";")
    df = pd.concat([df, ftemp], axis=0)

In [4]:
# Cabecero de los datos
df.head(5)

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,D27,V27,D28,V28,D29,V29,D30,V30,D31,V31
0,28,79,4,1,28079004_1_38,2010,1,12.0,V,15.0,...,16.0,V,21.0,V,22.0,V,17.0,V,15.0,V
1,28,79,4,1,28079004_1_38,2010,2,18.0,V,20.0,...,15.0,V,13.0,V,0.0,N,0.0,N,0.0,N
2,28,79,4,1,28079004_1_38,2010,3,13.0,V,15.0,...,14.0,V,16.0,V,15.0,V,13.0,V,14.0,V
3,28,79,4,1,28079004_1_38,2010,4,14.0,V,14.0,...,9.0,V,9.0,V,9.0,V,9.0,V,0.0,N
4,28,79,4,1,28079004_1_38,2010,5,8.0,V,8.0,...,9.0,V,9.0,V,9.0,V,9.0,V,9.0,V

Ahora, exportamos los datos a un csv para poder trabajar con ellos.

In [5]:
# Exportamos a csv los datos
df.to_csv('datos_total.csv', encoding='utf-8')